version: '3.8'

services:
  movies-app:
    build: .
    container_name: movies-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8080:8000"
    env_file:
          - .env.dev
  movies-db:
    image: postgres:11
    container_name: movies-db
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: