# Generated by Django 4.1.4 on 2022-12-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the movie", max_length=255),
                ),
                (
                    "desc",
                    models.CharField(
                        help_text="Description of the movie.", max_length=2024
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        help_text="Optional genre of the movie ",
                        max_length=255,
                    ),
                ),
                (
                    "year",
                    models.CharField(help_text="Date of publication", max_length=4),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("likes", models.IntegerField(help_text="Number of likes")),
                ("dislikes", models.IntegerField(help_text="Number of dislikes")),
            ],
        ),
    ]
