# Generated by Django 4.1.4 on 2022-12-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_movie_dislikes_remove_movie_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image",
                upload_to="covers/",
                verbose_name="Movie cover image",
            ),
        ),
    ]
