# Generated by Django 4.1.4 on 2022-12-22 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_movie_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="dislikes",
            field=models.ManyToManyField(
                help_text="Many user can dislike this movie and this movie can be disliked from different users",
                related_name="movie_dislikes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users who don't this a movie",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="likes",
            field=models.ManyToManyField(
                help_text="Many user can like this movie and this movie can be liked from different users",
                related_name="movie_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users who liked this a movie",
            ),
        ),
    ]
